apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  clusterIP: None
  ports:
    - name: redis
      port: 6379
  selector:
    app: redis

---
apiVersion: v1
kind: Service
metadata:
  name: redis-read
  labels:
    app: redis
    readonly: "true"
spec:
  clusterIP: None
  ports:
    - name: redis
      port: 6379
  selector:
    app: redis
