apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  selector:
    matchLabels:
      app: postgres
  replicas: 3
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.1-alpine3.19
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
          command:
            - bash
            - "-c"
            - |
              set -ex
              ordinal=${BASH_REMATCH[1]}
              if [[$ordinal -eq 0]]; then
                cp /var/lib/postgres/config/primary.conf /var/lib/postgres/data/postgres.conf
              else
                cp /var/lib/postgres/config/standby.conf /var/lib/postgres/data/postgres.conf
              fi
              cp /var/lib/postgres/config/pg_hba.conf /var/lib/postgres/data/pg_hba.conf
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgres/data
            - name: postgres-config
              mountPath: /var/lib/postgres/config
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres
        - name: postgres-config
          configMap:
            name: postgres
  volumeClaimTemplates:
    - metadata:
        name: postgres
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
