apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb
  selector:
    matchLabels:
      app: mongodb
  replicas: 3
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      initContainers:
        - name: init-mongodb
          image: mongo:7.0.8-jammy
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: MONGO_INITDB_ROOT_PASSWORD
          command: [bash, /data/db/config/init.sh]
          volumeMounts:
            - name: mongodb-config
              mountPath: /data/db/config
      containers:
        - name: mongodb
          image: mongo:7.0.8-jammy
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: MONGO_INITDB_ROOT_PASSWORD
          command: [mongod, --replset, rs0]
          volumeMounts:
            - name: mongodb
              mountPath: /data/db
      volumes:
        - name: mongodb-config
          configMap:
            name: mongodb
  volumeClaimTemplates:
    - metadata:
        name: mongodb
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
