apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
    type: hostpath
spec:
  storageClassName: local
  claimRef:
    name: mysql-pvc
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/location
